services:
  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_KRAFT_MODE: false
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    networks:
      - bat-budget-network

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - bat-budget-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      JWT_SECRET: this_is_a_very_secret_key
    depends_on:
      - kafka
    networks:
      - bat-budget-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/batdb
      SPRING_DATASOURCE_USERNAME: batuser
      SPRING_DATASOURCE_PASSWORD: batpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - kafka
      - redis
      - postgres
    networks:
      - bat-budget-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bat-budget-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: batcave
      POSTGRES_USER: batuser
      POSTGRES_PASSWORD: batpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bat-budget-network

  cache-service:
    build:
      context: ./cache-service
    container_name: cache-service
    ports:
      - "8083:8083"
    depends_on:
      - redis
    networks:
      - bat-budget-network

  persistence-service:
    build:
      context: ./persistence-service
    container_name: persistence-service
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/batdb
      SPRING_DATASOURCE_USERNAME: batuser
      SPRING_DATASOURCE_PASSWORD: batpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8082:8082"
    networks:
      - bat-budget-network

networks:
  bat-budget-network:

volumes:
  postgres-data: